# Tells the generator where the source files (.arb) are located.
arb-dir: lib/l10n

# Tells the generator how to name the main output file.
output-localization-file: app_localizations.dart

# Tells the generator to place output files in the standard directory
# where Flutter expects them.
output-dir: lib/generated/
untranslated-messages-file: lib/generated/untranslated_items.txt
