repo_url: "REPO_URL_PLACEHOLDER"
repo_name: "REPO_NAME_PLACEHOLDER"
repo_description: "REPO_DESC_PLACEHOLDER"

keystore: "fdroid.jks"
repo_keyalias: "fdroid"

keystorepass: "KEYSTORE_PASS_PLACEHOLDER"
keypass: "KEY_PASS_PLACEHOLDER"

keystore_passphrase: "KEYSTORE_PASS_PLACEHOLDER"
key_passphrase: "KEY_PASS_PLACEHOLDER"

# Standard-Details
keydname: "CN=F-Droid Repo, OU=F-Droid, O=F-Droid, L=Anywhere, C=US"
