import 'package:flutter/widgets.dart';

/// Small feature-local vocabulary until the plan surfaces are folded into the
/// app-wide ARB catalog. Every supported app language has explicit copy.
class ManualPlanText {
  ManualPlanText(BuildContext context)
      : _language = Localizations.localeOf(context).languageCode;

  final String _language;

  String get(String key) =>
      (_copy[_language] ?? _copy['en']!)[key] ?? _copy['en']![key] ?? key;

  static const _copy = <String, Map<String, String>>{
    'de': {
      'plans': 'Trainingspläne',
      'plan': 'Trainingsplan',
      'create': 'Plan erstellen',
      'edit': 'Plan bearbeiten',
      'name': 'Name',
      'week': 'Wochenplan',
      'sequence': 'Sequenz',
      'length': 'Länge',
      'days': 'Tage',
      'rest': 'Ruhetag',
      'save': 'Speichern',
      'saveActivate': 'Speichern und aktivieren',
      'active': 'Aktiv',
      'activate': 'Aktivieren',
      'deactivate': 'Deaktivieren',
      'resume': 'Fortsetzen',
      'restart': 'Neu beginnen',
      'cancel': 'Abbrechen',
      'today': 'Heute',
      'start': 'Workout starten',
      'skip': 'Überspringen',
      'planned': 'Geplant',
      'open': 'Offen',
      'nextUp': 'Als Nächstes',
      'startPastConfirm': 'Diese vergangene Planeinheit jetzt nachholen?',
      'ongoing': 'Läuft',
      'completed': 'Absolviert',
      'partial': 'Teilweise absolviert',
      'skipped': 'Übersprungen',
      'nextCycle': 'Ab nächstem Zyklus',
      'fromToday': 'Ab heute',
      'applyWhen': 'Wann soll diese Änderung gelten?',
      'chooseRoutine': 'Routine wählen',
      'noPlan': 'Noch kein Trainingsplan',
      'history': 'Versionen',
      'version': 'Version',
      'needsWorkout': 'Wähle mindestens eine Routine aus.',
      'missingName': 'Gib dem Plan einen Namen.',
      'confirmSkip': 'Diese Einheit ausdrücklich überspringen?',
      'routineChanged': 'Routine geändert',
      'routineOnly': 'Nur Routine ändern',
      'updatePlan': 'Auch im Plan übernehmen',
      'previous': 'Zurück',
      'next': 'Weiter',
    },
    'en': {
      'plans': 'Training plans',
      'plan': 'Training plan',
      'create': 'Create plan',
      'edit': 'Edit plan',
      'name': 'Name',
      'week': 'Weekly plan',
      'sequence': 'Sequence',
      'length': 'Length',
      'days': 'days',
      'rest': 'Rest day',
      'save': 'Save',
      'saveActivate': 'Save and activate',
      'active': 'Active',
      'activate': 'Activate',
      'deactivate': 'Deactivate',
      'resume': 'Resume',
      'restart': 'Start over',
      'cancel': 'Cancel',
      'today': 'Today',
      'start': 'Start workout',
      'skip': 'Skip',
      'planned': 'Planned',
      'open': 'Open',
      'nextUp': 'Up next',
      'startPastConfirm': 'Make up this past planned session now?',
      'ongoing': 'In progress',
      'completed': 'Completed',
      'partial': 'Partly completed',
      'skipped': 'Skipped',
      'nextCycle': 'Next cycle',
      'fromToday': 'Today',
      'applyWhen': 'When should this change take effect?',
      'chooseRoutine': 'Choose routine',
      'noPlan': 'No training plan yet',
      'history': 'Versions',
      'version': 'Version',
      'needsWorkout': 'Choose at least one routine.',
      'missingName': 'Give your plan a name.',
      'confirmSkip': 'Explicitly skip this session?',
      'routineChanged': 'Routine changed',
      'routineOnly': 'Change routine only',
      'updatePlan': 'Update plan too',
      'previous': 'Previous',
      'next': 'Next',
    },
    'fr': {
      'plans': 'Plans d’entraînement',
      'plan': 'Plan d’entraînement',
      'create': 'Créer un plan',
      'edit': 'Modifier le plan',
      'name': 'Nom',
      'week': 'Plan hebdomadaire',
      'sequence': 'Séquence',
      'length': 'Durée',
      'days': 'jours',
      'rest': 'Repos',
      'save': 'Enregistrer',
      'saveActivate': 'Enregistrer et activer',
      'active': 'Actif',
      'activate': 'Activer',
      'deactivate': 'Désactiver',
      'resume': 'Reprendre',
      'restart': 'Recommencer',
      'cancel': 'Annuler',
      'today': 'Aujourd’hui',
      'start': 'Commencer',
      'skip': 'Passer',
      'planned': 'Prévu',
      'open': 'Ouvert',
      'nextUp': 'À suivre',
      'startPastConfirm': 'Rattraper cette séance passée maintenant ?',
      'ongoing': 'En cours',
      'completed': 'Terminé',
      'partial': 'Partiellement terminé',
      'skipped': 'Passé',
      'nextCycle': 'Cycle suivant',
      'fromToday': 'Dès aujourd’hui',
      'applyWhen': 'Quand appliquer ce changement ?',
      'chooseRoutine': 'Choisir une routine',
      'noPlan': 'Aucun plan',
      'history': 'Versions',
      'version': 'Version',
      'needsWorkout': 'Choisissez au moins une routine.',
      'missingName': 'Nommez votre plan.',
      'confirmSkip': 'Passer volontairement cette séance ?',
      'routineChanged': 'Routine modifiée',
      'routineOnly': 'Modifier la routine seulement',
      'updatePlan': 'Mettre aussi le plan à jour',
      'previous': 'Précédent',
      'next': 'Suivant',
    },
    'it': {
      'plans': 'Piani di allenamento',
      'plan': 'Piano di allenamento',
      'create': 'Crea piano',
      'edit': 'Modifica piano',
      'name': 'Nome',
      'week': 'Piano settimanale',
      'sequence': 'Sequenza',
      'length': 'Durata',
      'days': 'giorni',
      'rest': 'Riposo',
      'save': 'Salva',
      'saveActivate': 'Salva e attiva',
      'active': 'Attivo',
      'activate': 'Attiva',
      'deactivate': 'Disattiva',
      'resume': 'Riprendi',
      'restart': 'Ricomincia',
      'cancel': 'Annulla',
      'today': 'Oggi',
      'start': 'Inizia allenamento',
      'skip': 'Salta',
      'planned': 'Previsto',
      'open': 'Aperto',
      'nextUp': 'Prossimo',
      'startPastConfirm': 'Recuperare ora questa sessione passata?',
      'ongoing': 'In corso',
      'completed': 'Completato',
      'partial': 'Parzialmente completato',
      'skipped': 'Saltato',
      'nextCycle': 'Prossimo ciclo',
      'fromToday': 'Da oggi',
      'applyWhen': 'Quando applicare la modifica?',
      'chooseRoutine': 'Scegli routine',
      'noPlan': 'Nessun piano',
      'history': 'Versioni',
      'version': 'Versione',
      'needsWorkout': 'Scegli almeno una routine.',
      'missingName': 'Dai un nome al piano.',
      'confirmSkip': 'Saltare questa sessione?',
      'routineChanged': 'Routine modificata',
      'routineOnly': 'Modifica solo la routine',
      'updatePlan': 'Aggiorna anche il piano',
      'previous': 'Precedente',
      'next': 'Avanti',
    },
    'ja': {
      'plans': 'トレーニングプラン',
      'plan': 'トレーニングプラン',
      'create': 'プランを作成',
      'edit': 'プランを編集',
      'name': '名前',
      'week': '週間プラン',
      'sequence': 'シーケンス',
      'length': '日数',
      'days': '日',
      'rest': '休息日',
      'save': '保存',
      'saveActivate': '保存して有効化',
      'active': '有効',
      'activate': '有効化',
      'deactivate': '無効化',
      'resume': '再開',
      'restart': '最初から',
      'cancel': 'キャンセル',
      'today': '今日',
      'start': 'ワークアウト開始',
      'skip': 'スキップ',
      'planned': '予定',
      'open': '未完了',
      'nextUp': '次の予定',
      'startPastConfirm': '過去の予定を今から実行しますか？',
      'ongoing': '進行中',
      'completed': '完了',
      'partial': '一部完了',
      'skipped': 'スキップ済み',
      'nextCycle': '次のサイクル',
      'fromToday': '今日から',
      'applyWhen': '変更をいつ反映しますか？',
      'chooseRoutine': 'ルーティンを選択',
      'noPlan': 'プランはまだありません',
      'history': 'バージョン',
      'version': 'バージョン',
      'needsWorkout': 'ルーティンを1つ以上選択してください。',
      'missingName': 'プラン名を入力してください。',
      'confirmSkip': 'この予定をスキップしますか？',
      'routineChanged': 'ルーティンを変更しました',
      'routineOnly': 'ルーティンのみ変更',
      'updatePlan': 'プランにも反映',
      'previous': '前へ',
      'next': '次へ',
    },
  };
}
