import 'package:flutter/widgets.dart';

/// Small feature-local vocabulary until the plan surfaces are folded into the
/// app-wide ARB catalog. Every supported app language has explicit copy.
class ManualPlanText {
  ManualPlanText(BuildContext context)
      : _language = Localizations.localeOf(context).languageCode;

  final String _language;

  String get(String key) =>
      (_copy[_language] ?? _copy['en']!)[key] ?? _copy['en']![key] ?? key;

  static const _copy = <String, Map<String, String>>{
    'de': {
      'plans': 'Trainingspläne',
      'plan': 'Trainingsplan',
      'create': 'Plan erstellen',
      'edit': 'Plan bearbeiten',
      'name': 'Name',
      'week': 'Wochenplan',
      'sequence': 'Sequenz',
      'length': 'Länge',
      'days': 'Tage',
      'rest': 'Ruhetag',
      'save': 'Speichern',
      'saveActivate': 'Speichern und aktivieren',
      'active': 'Aktiv',
      'activate': 'Aktivieren',
      'deactivate': 'Deaktivieren',
      'resume': 'Fortsetzen',
      'restart': 'Neu beginnen',
      'cancel': 'Abbrechen',
      'today': 'Heute',
      'start': 'Workout starten',
      'viewWorkout': 'Workout ansehen',
      'skip': 'Überspringen',
      'planned': 'Geplant',
      'open': 'Offen',
      'nextUp': 'Als Nächstes',
      'startPastConfirm': 'Diese vergangene Planeinheit jetzt nachholen?',
      'ongoing': 'Läuft',
      'completed': 'Absolviert',
      'partial': 'Teilweise absolviert',
      'skipped': 'Übersprungen',
      'nextCycle': 'Ab nächstem Zyklus',
      'fromToday': 'Ab heute',
      'applyWhen': 'Wann soll diese Änderung gelten?',
      'chooseRoutine': 'Routine wählen',
      'noPlan': 'Noch kein Trainingsplan',
      'history': 'Versionen',
      'version': 'Version',
      'needsWorkout': 'Wähle mindestens eine Routine aus.',
      'missingName': 'Gib dem Plan einen Namen.',
      'confirmSkip': 'Diese Einheit ausdrücklich überspringen?',
      'routineChanged': 'Routine geändert',
      'routineOnly': 'Nur Routine ändern',
      'updatePlan': 'Auch im Plan übernehmen',
      'previous': 'Zurück',
      'next': 'Weiter',
      'inactive': 'Inaktiv',
      'savedPlans': 'Gespeicherte Pläne',
      'schedule': 'Kalender',
      'planOverview': 'Planübersicht',
      'weekView': 'Woche',
      'managePlan': 'Plan verwalten',
      'weekPlanExplanation':
          'Die Einheiten bleiben ihren Wochentagen zugeordnet. Nicht absolvierte Tage werden nicht automatisch nachgeholt.',
      'sequencePlanExplanation':
          'Die Sequenz geht erst weiter, wenn du die aktuelle Einheit absolvierst, teilweise abschließt oder bewusst überspringst.',
      'activatePlanTitle': 'Plan aktivieren',
      'activatePlanBody':
          'Du kannst an deiner letzten Position weitermachen oder den Plan heute neu beginnen.',
      'resumeDescription':
          'An der zuletzt gespeicherten Position weitertrainieren',
      'restartDescription':
          'Die Sequenz beziehungsweise Woche heute neu beginnen',
      'deactivatePlanTitle': 'Plan pausieren?',
      'deactivatePlanBody':
          'Dein Verlauf und alle absolvierten Einheiten bleiben erhalten.',
      'skipExplanation':
          'Die Einheit wird als übersprungen dokumentiert und der Plan läuft anschließend weiter.',
      'startPastBody':
          'Das Workout startet jetzt, bleibt im Plan aber dem ursprünglich vorgesehenen Tag zugeordnet.',
      'historyExplanation':
          'Jede Änderung erzeugt eine neue Version. Vergangene Einheiten behalten ihre damaligen Vorgaben.',
      'noPlanDescription':
          'Erstelle einen Wochenplan oder eine fortlaufende Sequenz aus deinen vorhandenen Routinen.',
      'startShort': 'Starten',
      'restDescription': 'Heute ist bewusst keine Trainingseinheit vorgesehen.',
      'completedDescription':
          'Alle vorgesehenen Sätze wurden absolviert. Zusätzliche Sätze bleiben ebenfalls erhalten.',
      'partialDescription':
          'Das Workout wurde begonnen und mit den tatsächlich absolvierten Sätzen gespeichert.',
      'skippedDescription': 'Diese Einheit wurde bewusst übersprungen.',
      'futureDescription':
          'Diese Einheit ist für den ausgewählten Tag vorgesehen.',
      'todayDescription': 'Diese Einheit ist heute als Nächstes vorgesehen.',
      'pastOpenDescription':
          'Diese Einheit ist noch offen und kann jetzt bewusst gestartet oder übersprungen werden.',
      'notStarted': 'Noch nicht aktiv',
      'beforePlanStart': 'Vor Planbeginn',
      'basics': 'Grundlagen',
      'day': 'Tag',
      'exercises': 'Übungen',
      'restPickerDescription': 'Keine Routine an diesem Tag',
      'weekEditorExplanation':
          'Die sieben Tage wiederholen sich jede Woche und bleiben festen Wochentagen zugeordnet.',
      'weekEditorShort': 'Feste Wochentage, jede Woche.',
      'sequenceEditorExplanation':
          'Eine Sequenz läuft unabhängig von Wochentagen in der festgelegten Reihenfolge weiter.',
      'sequenceEditorShort': 'Tag für Tag in eigener Reihenfolge.',
      'editorScheduleHint':
          'Tippe auf einen Tag, um eine Routine zuzuweisen oder ihn als Ruhetag festzulegen.',
      'shorter': 'Sequenz verkürzen',
      'longer': 'Sequenz verlängern',
      'editRoutine': 'Routine bearbeiten',
      'addDay': 'Tag hinzufügen',
      'removeDay': 'Tag entfernen',
      'hubNoPlanDescription': 'Erstelle deinen eigenen Trainingsrhythmus',
      'hubNoUpcomingWorkout': 'Aktuell ist keine Einheit offen',
    },
    'en': {
      'plans': 'Training plans',
      'plan': 'Training plan',
      'create': 'Create plan',
      'edit': 'Edit plan',
      'name': 'Name',
      'week': 'Weekly plan',
      'sequence': 'Sequence',
      'length': 'Length',
      'days': 'days',
      'rest': 'Rest day',
      'save': 'Save',
      'saveActivate': 'Save and activate',
      'active': 'Active',
      'activate': 'Activate',
      'deactivate': 'Deactivate',
      'resume': 'Resume',
      'restart': 'Start over',
      'cancel': 'Cancel',
      'today': 'Today',
      'start': 'Start workout',
      'viewWorkout': 'View workout',
      'skip': 'Skip',
      'planned': 'Planned',
      'open': 'Open',
      'nextUp': 'Up next',
      'startPastConfirm': 'Make up this past planned session now?',
      'ongoing': 'In progress',
      'completed': 'Completed',
      'partial': 'Partly completed',
      'skipped': 'Skipped',
      'nextCycle': 'Next cycle',
      'fromToday': 'Today',
      'applyWhen': 'When should this change take effect?',
      'chooseRoutine': 'Choose routine',
      'noPlan': 'No training plan yet',
      'history': 'Versions',
      'version': 'Version',
      'needsWorkout': 'Choose at least one routine.',
      'missingName': 'Give your plan a name.',
      'confirmSkip': 'Explicitly skip this session?',
      'routineChanged': 'Routine changed',
      'routineOnly': 'Change routine only',
      'updatePlan': 'Update plan too',
      'previous': 'Previous',
      'next': 'Next',
      'inactive': 'Inactive',
      'savedPlans': 'Saved plans',
      'schedule': 'Calendar',
      'planOverview': 'Plan overview',
      'weekView': 'Week',
      'managePlan': 'Manage plan',
      'weekPlanExplanation':
          'Sessions stay assigned to their weekdays. Missed days are not moved automatically.',
      'sequencePlanExplanation':
          'The sequence advances only after you complete, partly complete, or explicitly skip the current session.',
      'activatePlanTitle': 'Activate plan',
      'activatePlanBody':
          'Continue from the saved position or start the plan again today.',
      'resumeDescription': 'Continue from the last saved position',
      'restartDescription': 'Restart the sequence or week today',
      'deactivatePlanTitle': 'Pause this plan?',
      'deactivatePlanBody':
          'Your history and completed sessions remain available.',
      'skipExplanation':
          'The session is recorded as skipped and the plan then moves on.',
      'startPastBody':
          'The workout starts now but remains assigned to its original planned day.',
      'historyExplanation':
          'Every edit creates a version. Past sessions keep the instructions they had at the time.',
      'noPlanDescription':
          'Build a weekly plan or an ongoing sequence from your saved routines.',
      'startShort': 'Start',
      'restDescription':
          'No training session is intentionally planned for this day.',
      'completedDescription':
          'All prescribed sets were completed. Extra sets are kept as well.',
      'partialDescription':
          'The workout was started and saved with the sets you actually completed.',
      'skippedDescription': 'This session was explicitly skipped.',
      'futureDescription': 'This session is planned for the selected day.',
      'todayDescription': 'This is the next session planned for today.',
      'pastOpenDescription':
          'This session is still open. Start or explicitly skip it now.',
      'notStarted': 'Not active yet',
      'beforePlanStart': 'Before plan start',
      'basics': 'Basics',
      'day': 'Day',
      'exercises': 'exercises',
      'restPickerDescription': 'No routine on this day',
      'weekEditorExplanation':
          'The seven days repeat each week and stay assigned to fixed weekdays.',
      'weekEditorShort': 'Fixed weekdays, repeated weekly.',
      'sequenceEditorExplanation':
          'A sequence continues in order independently of weekdays.',
      'sequenceEditorShort': 'Day by day in its own order.',
      'editorScheduleHint':
          'Tap a day to assign a routine or make it a rest day.',
      'shorter': 'Shorten sequence',
      'longer': 'Lengthen sequence',
      'editRoutine': 'Edit routine',
      'addDay': 'Add day',
      'removeDay': 'Remove day',
      'hubNoPlanDescription': 'Build your own training rhythm',
      'hubNoUpcomingWorkout': 'No session is currently due',
    },
    'fr': {
      'plans': 'Plans d’entraînement',
      'plan': 'Plan d’entraînement',
      'create': 'Créer un plan',
      'edit': 'Modifier le plan',
      'name': 'Nom',
      'week': 'Plan hebdomadaire',
      'sequence': 'Séquence',
      'length': 'Durée',
      'days': 'jours',
      'rest': 'Repos',
      'save': 'Enregistrer',
      'saveActivate': 'Enregistrer et activer',
      'active': 'Actif',
      'activate': 'Activer',
      'deactivate': 'Désactiver',
      'resume': 'Reprendre',
      'restart': 'Recommencer',
      'cancel': 'Annuler',
      'today': 'Aujourd’hui',
      'start': 'Commencer',
      'viewWorkout': 'Voir l’entraînement',
      'skip': 'Passer',
      'planned': 'Prévu',
      'open': 'Ouvert',
      'nextUp': 'À suivre',
      'startPastConfirm': 'Rattraper cette séance passée maintenant ?',
      'ongoing': 'En cours',
      'completed': 'Terminé',
      'partial': 'Partiellement terminé',
      'skipped': 'Passé',
      'nextCycle': 'Cycle suivant',
      'fromToday': 'Dès aujourd’hui',
      'applyWhen': 'Quand appliquer ce changement ?',
      'chooseRoutine': 'Choisir une routine',
      'noPlan': 'Aucun plan',
      'history': 'Versions',
      'version': 'Version',
      'needsWorkout': 'Choisissez au moins une routine.',
      'missingName': 'Nommez votre plan.',
      'confirmSkip': 'Passer volontairement cette séance ?',
      'routineChanged': 'Routine modifiée',
      'routineOnly': 'Modifier la routine seulement',
      'updatePlan': 'Mettre aussi le plan à jour',
      'previous': 'Précédent',
      'next': 'Suivant',
      'inactive': 'Inactif',
      'savedPlans': 'Plans enregistrés',
      'schedule': 'Calendrier',
      'planOverview': 'Vue du plan',
      'weekView': 'Semaine',
      'managePlan': 'Gérer le plan',
      'weekPlanExplanation':
          'Les séances restent associées à leurs jours. Les jours manqués ne sont pas déplacés automatiquement.',
      'sequencePlanExplanation':
          'La séquence avance uniquement après avoir terminé, partiellement terminé ou passé la séance en cours.',
      'activatePlanTitle': 'Activer le plan',
      'activatePlanBody':
          'Reprenez à la dernière position ou recommencez le plan aujourd’hui.',
      'resumeDescription': 'Continuer à la dernière position enregistrée',
      'restartDescription': 'Recommencer la séquence ou la semaine aujourd’hui',
      'deactivatePlanTitle': 'Mettre ce plan en pause ?',
      'deactivatePlanBody':
          'Votre historique et les séances terminées sont conservés.',
      'skipExplanation':
          'La séance sera notée comme passée, puis le plan continuera.',
      'startPastBody':
          'La séance démarre maintenant mais reste associée à son jour initial.',
      'historyExplanation':
          'Chaque modification crée une version. Les séances passées conservent leurs consignes.',
      'noPlanDescription':
          'Créez un plan hebdomadaire ou une séquence avec vos routines.',
      'startShort': 'Démarrer',
      'restDescription': 'Aucune séance n’est prévue volontairement ce jour.',
      'completedDescription':
          'Toutes les séries prévues ont été réalisées. Les séries supplémentaires sont conservées.',
      'partialDescription':
          'La séance a été commencée et enregistrée avec les séries réalisées.',
      'skippedDescription': 'Cette séance a été volontairement passée.',
      'futureDescription': 'Cette séance est prévue pour le jour sélectionné.',
      'todayDescription': 'C’est la prochaine séance prévue aujourd’hui.',
      'pastOpenDescription':
          'Cette séance est encore ouverte. Démarrez-la ou passez-la explicitement.',
      'notStarted': 'Pas encore actif',
      'beforePlanStart': 'Avant le début du plan',
      'basics': 'Principes',
      'day': 'Jour',
      'exercises': 'exercices',
      'restPickerDescription': 'Aucune routine ce jour',
      'weekEditorExplanation':
          'Les sept jours se répètent chaque semaine et restent associés aux jours fixes.',
      'weekEditorShort': 'Jours fixes, répétés chaque semaine.',
      'sequenceEditorExplanation':
          'Une séquence continue dans l’ordre, indépendamment des jours de la semaine.',
      'sequenceEditorShort': 'Jour après jour, dans son propre ordre.',
      'editorScheduleHint':
          'Touchez un jour pour attribuer une routine ou définir un jour de repos.',
      'shorter': 'Raccourcir la séquence',
      'longer': 'Allonger la séquence',
      'editRoutine': 'Modifier la routine',
      'addDay': 'Ajouter un jour',
      'removeDay': 'Supprimer le jour',
      'hubNoPlanDescription': 'Créez votre propre rythme d’entraînement',
      'hubNoUpcomingWorkout': 'Aucune séance n’est actuellement prévue',
    },
    'it': {
      'plans': 'Piani di allenamento',
      'plan': 'Piano di allenamento',
      'create': 'Crea piano',
      'edit': 'Modifica piano',
      'name': 'Nome',
      'week': 'Piano settimanale',
      'sequence': 'Sequenza',
      'length': 'Durata',
      'days': 'giorni',
      'rest': 'Riposo',
      'save': 'Salva',
      'saveActivate': 'Salva e attiva',
      'active': 'Attivo',
      'activate': 'Attiva',
      'deactivate': 'Disattiva',
      'resume': 'Riprendi',
      'restart': 'Ricomincia',
      'cancel': 'Annulla',
      'today': 'Oggi',
      'start': 'Inizia allenamento',
      'viewWorkout': 'Visualizza allenamento',
      'skip': 'Salta',
      'planned': 'Previsto',
      'open': 'Aperto',
      'nextUp': 'Prossimo',
      'startPastConfirm': 'Recuperare ora questa sessione passata?',
      'ongoing': 'In corso',
      'completed': 'Completato',
      'partial': 'Parzialmente completato',
      'skipped': 'Saltato',
      'nextCycle': 'Prossimo ciclo',
      'fromToday': 'Da oggi',
      'applyWhen': 'Quando applicare la modifica?',
      'chooseRoutine': 'Scegli routine',
      'noPlan': 'Nessun piano',
      'history': 'Versioni',
      'version': 'Versione',
      'needsWorkout': 'Scegli almeno una routine.',
      'missingName': 'Dai un nome al piano.',
      'confirmSkip': 'Saltare questa sessione?',
      'routineChanged': 'Routine modificata',
      'routineOnly': 'Modifica solo la routine',
      'updatePlan': 'Aggiorna anche il piano',
      'previous': 'Precedente',
      'next': 'Avanti',
      'inactive': 'Inattivo',
      'savedPlans': 'Piani salvati',
      'schedule': 'Calendario',
      'planOverview': 'Panoramica piano',
      'weekView': 'Settimana',
      'managePlan': 'Gestisci piano',
      'weekPlanExplanation':
          'Le sessioni restano assegnate ai giorni della settimana. I giorni saltati non vengono spostati automaticamente.',
      'sequencePlanExplanation':
          'La sequenza avanza solo dopo aver completato, completato in parte o saltato esplicitamente la sessione corrente.',
      'activatePlanTitle': 'Attiva piano',
      'activatePlanBody':
          'Continua dall’ultima posizione o ricomincia il piano oggi.',
      'resumeDescription': 'Continua dall’ultima posizione salvata',
      'restartDescription': 'Ricomincia oggi la sequenza o la settimana',
      'deactivatePlanTitle': 'Mettere in pausa il piano?',
      'deactivatePlanBody':
          'La cronologia e le sessioni completate restano disponibili.',
      'skipExplanation':
          'La sessione viene registrata come saltata e il piano prosegue.',
      'startPastBody':
          'L’allenamento inizia ora ma resta associato al giorno originario.',
      'historyExplanation':
          'Ogni modifica crea una versione. Le sessioni passate mantengono le istruzioni originali.',
      'noPlanDescription':
          'Crea un piano settimanale o una sequenza usando le tue routine.',
      'startShort': 'Avvia',
      'restDescription': 'Per questo giorno non è prevista alcuna sessione.',
      'completedDescription':
          'Tutte le serie previste sono state completate. Anche le serie extra vengono conservate.',
      'partialDescription':
          'L’allenamento è stato iniziato e salvato con le serie effettivamente completate.',
      'skippedDescription': 'Questa sessione è stata saltata esplicitamente.',
      'futureDescription':
          'Questa sessione è prevista per il giorno selezionato.',
      'todayDescription': 'Questa è la prossima sessione prevista per oggi.',
      'pastOpenDescription':
          'Questa sessione è ancora aperta. Avviala o saltala esplicitamente.',
      'notStarted': 'Non ancora attivo',
      'beforePlanStart': 'Prima dell’inizio',
      'basics': 'Impostazioni base',
      'day': 'Giorno',
      'exercises': 'esercizi',
      'restPickerDescription': 'Nessuna routine in questo giorno',
      'weekEditorExplanation':
          'I sette giorni si ripetono ogni settimana e restano assegnati ai giorni fissi.',
      'weekEditorShort': 'Giorni fissi, ripetuti ogni settimana.',
      'sequenceEditorExplanation':
          'Una sequenza continua in ordine indipendentemente dai giorni della settimana.',
      'sequenceEditorShort': 'Giorno per giorno, nel proprio ordine.',
      'editorScheduleHint':
          'Tocca un giorno per assegnare una routine o renderlo un giorno di riposo.',
      'shorter': 'Riduci sequenza',
      'longer': 'Estendi sequenza',
      'editRoutine': 'Modifica routine',
      'addDay': 'Aggiungi giorno',
      'removeDay': 'Rimuovi giorno',
      'hubNoPlanDescription': 'Crea il tuo ritmo di allenamento',
      'hubNoUpcomingWorkout': 'Nessuna sessione è attualmente prevista',
    },
    'ja': {
      'plans': 'トレーニングプラン',
      'plan': 'トレーニングプラン',
      'create': 'プランを作成',
      'edit': 'プランを編集',
      'name': '名前',
      'week': '週間プラン',
      'sequence': 'シーケンス',
      'length': '日数',
      'days': '日',
      'rest': '休息日',
      'save': '保存',
      'saveActivate': '保存して有効化',
      'active': '有効',
      'activate': '有効化',
      'deactivate': '無効化',
      'resume': '再開',
      'restart': '最初から',
      'cancel': 'キャンセル',
      'today': '今日',
      'start': 'ワークアウト開始',
      'viewWorkout': 'ワークアウトを見る',
      'skip': 'スキップ',
      'planned': '予定',
      'open': '未完了',
      'nextUp': '次の予定',
      'startPastConfirm': '過去の予定を今から実行しますか？',
      'ongoing': '進行中',
      'completed': '完了',
      'partial': '一部完了',
      'skipped': 'スキップ済み',
      'nextCycle': '次のサイクル',
      'fromToday': '今日から',
      'applyWhen': '変更をいつ反映しますか？',
      'chooseRoutine': 'ルーティンを選択',
      'noPlan': 'プランはまだありません',
      'history': 'バージョン',
      'version': 'バージョン',
      'needsWorkout': 'ルーティンを1つ以上選択してください。',
      'missingName': 'プラン名を入力してください。',
      'confirmSkip': 'この予定をスキップしますか？',
      'routineChanged': 'ルーティンを変更しました',
      'routineOnly': 'ルーティンのみ変更',
      'updatePlan': 'プランにも反映',
      'previous': '前へ',
      'next': '次へ',
      'inactive': '無効',
      'savedPlans': '保存済みプラン',
      'schedule': 'カレンダー',
      'planOverview': 'プラン概要',
      'weekView': '週',
      'managePlan': 'プランを管理',
      'weekPlanExplanation': '各セッションは曜日に固定されます。実施しなかった日は自動で移動しません。',
      'sequencePlanExplanation': '現在のセッションを完了、一部完了、または明示的にスキップした後に次へ進みます。',
      'activatePlanTitle': 'プランを有効化',
      'activatePlanBody': '保存位置から続けるか、今日から最初に戻れます。',
      'resumeDescription': '最後に保存した位置から続ける',
      'restartDescription': '今日からシーケンスまたは週を再開する',
      'deactivatePlanTitle': 'プランを一時停止しますか？',
      'deactivatePlanBody': '履歴と完了済みセッションは保持されます。',
      'skipExplanation': 'スキップとして記録され、その後プランは次へ進みます。',
      'startPastBody': 'ワークアウトは今開始されますが、元の予定日に関連付けられます。',
      'historyExplanation': '変更ごとに新しいバージョンが作成され、過去の内容は保持されます。',
      'noPlanDescription': '保存済みルーティンから週間プランまたはシーケンスを作成します。',
      'startShort': '開始',
      'restDescription': 'この日は意図的にトレーニングを予定していません。',
      'completedDescription': '予定されたセットをすべて完了しました。追加セットも保持されます。',
      'partialDescription': '実施したセットを含めて一部完了として保存されました。',
      'skippedDescription': 'このセッションは明示的にスキップされました。',
      'futureDescription': '選択した日にこのセッションが予定されています。',
      'todayDescription': '今日の次の予定セッションです。',
      'pastOpenDescription': 'このセッションは未完了です。開始またはスキップできます。',
      'notStarted': 'まだ有効ではありません',
      'beforePlanStart': 'プラン開始前',
      'basics': '基本設定',
      'day': '日',
      'exercises': '種目',
      'restPickerDescription': 'この日はルーティンなし',
      'weekEditorExplanation': '7日間が毎週繰り返され、各セッションは曜日に固定されます。',
      'weekEditorShort': '固定曜日で毎週繰り返します。',
      'sequenceEditorExplanation': '曜日に関係なく、設定した順序でシーケンスが進みます。',
      'sequenceEditorShort': '独自の順番で1日ずつ進みます。',
      'editorScheduleHint': '日をタップしてルーティンまたは休息日を設定します。',
      'shorter': 'シーケンスを短くする',
      'longer': 'シーケンスを長くする',
      'editRoutine': 'ルーティンを編集',
      'addDay': '日を追加',
      'removeDay': '日を削除',
      'hubNoPlanDescription': '自分のトレーニングリズムを作成',
      'hubNoUpcomingWorkout': '現在予定されているセッションはありません',
    },
  };
}
